name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Node Setup
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release
      - uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
